[versions]
agp = "8.13.0"
android-compileSdk = "36"
android-minSdk = "21"
android-targetSdk = "36"
kotlin = "2.2.21"
compose-plugin = "1.9.3"
kotlinx-serialization = "1.9.0"
maven-publish = "0.34.0"
ksp = "2.2.20-2.0.3"
kotlinx-coroutines = "1.10.2"
kotlin-js = "2025.11.5" # https://central.sonatype.com/artifact/org.jetbrains.kotlin-wrappers/kotlin-js

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-gradle = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
compose-compiler-gradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-gradle = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose-plugin" }
maven-publish-gradle = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }

emulator-wtf-gradle = "wtf.emulator:gradle-plugin:0.0.11"

androidx-core = "androidx.core:core-ktx:1.17.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
androidx-fragment = "androidx.fragment:fragment-ktx:1.8.9"
androidx-fragment-compose = "androidx.fragment:fragment-compose:1.8.9"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
androidx-splashscreen = "androidx.core:core-splashscreen:1.2.0"

# Used for interoperability testing in the main Enro test suite
androidx-navigation-fragment = "androidx.navigation:navigation-fragment-ktx:2.9.6"
androidx-navigation-ui = "androidx.navigation:navigation-ui-ktx:2.9.6"
androidx-navigation-event = "androidx.navigationevent:navigationevent:1.0.0-rc01"

androidx-activity = "androidx.activity:activity-ktx:1.11.0"
compose-activity = "androidx.activity:activity-compose:1.11.0"

androidx-viewmodel = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel:2.9.6"
androidx-lifecycle-process = "androidx.lifecycle:lifecycle-process:2.9.4"

androidx-savedState = "org.jetbrains.androidx.savedstate:savedstate:1.3.6"
androidx-savedState-compose = "org.jetbrains.androidx.savedstate:savedstate-compose:1.3.6"

compose-compiler = "androidx.compose.compiler:compiler:1.5.15"
compose-foundation = "androidx.compose.foundation:foundation:1.9.4"
compose-foundationLayout = "androidx.compose.foundation:foundation-layout:1.9.4"
compose-ui = "androidx.compose.ui:ui:1.9.4"
compose-uiTooling = "androidx.compose.ui:ui-tooling:1.9.4"
compose-ui-backhandler = "org.jetbrains.compose.ui:ui-backhandler:1.9.3"
compose-preview = "androidx.compose.ui:ui-tooling-preview:1.9.4"
compose-runtime = "androidx.compose.runtime:runtime:1.9.4"
compose-runtimeAnnotation = "androidx.compose.runtime:runtime-annotation:1.9.4"
compose-livedata = "androidx.compose.runtime:runtime-livedata:1.9.4"
compose-material = "androidx.compose.material:material:1.9.4"
compose-material3 = "androidx.compose.material:material3:1.7.8"
compose-lifecycle = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose:2.9.6"
compose-bundle = "org.jetbrains.androidx.core:core-bundle:1.0.1"
compose-viewmodel = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose:2.9.6"


compose-accompanist-systemUiController = "com.google.accompanist:accompanist-systemuicontroller:0.36.0"

compose-materialIcons = "androidx.compose.material:material-icons-core:1.7.8"
compose-materialIconsExtended = "androidx.compose.material:material-icons-extended:1.7.8"

kotlin-stdLib = "org.jetbrains.kotlin:kotlin-stdlib:2.2.21"
kotlin-reflect = "org.jetbrains.kotlin:kotlin-reflect:2.2.0"
kotlin-js = { module = "org.jetbrains.kotlin-wrappers:kotlin-js", version.ref = "kotlin-js" }

kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

thauvin-urlencoder = "net.thauvin.erik.urlencoder:urlencoder-lib:1.6.0"

leakcanary = "com.squareup.leakcanary:leakcanary-android:2.14"

testing-junit = "junit:junit:4.13.2"
testing-robolectric = "org.robolectric:robolectric:4.16"

testing-androidx-junit = "androidx.test.ext:junit:1.3.0"
testing-androidx-core = "androidx.test:core:1.7.0"
testing-androidx-runner = "androidx.test:runner:1.7.0"
testing-androidx-orchestrator = "androidx.test:orchestrator:1.6.1"
testing-androidx-espresso = "androidx.test.espresso:espresso-core:3.7.0"
testing-androidx-espressoRecyclerView = "androidx.test.espresso:espresso-contrib:3.7.0"
testing-androidx-espressoIntents = "androidx.test.espresso:espresso-intents:3.7.0"
testing-androidx-fragment = "androidx.fragment:fragment-testing:1.8.9"
testing-androidx-compose = "androidx.compose.ui:ui-test-junit4:1.9.4"

testing-leakcanary-instrumentation = "com.squareup.leakcanary:leakcanary-android-instrumentation:2.14"

testing-archunit = "com.tngtech.archunit:archunit:1.4.1"

processing-ksp-gradle = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
processing-ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
processing-incremental = "net.ltgt.gradle.incap:incap:1.0.0"
processing-incrementalProcessor = "net.ltgt.gradle.incap:incap-processor:1.0.0"
processing-autoService = "com.google.auto.service:auto-service:1.1.1"
processing-javaPoet = "com.squareup:javapoet:1.13.0"
processing-kotlinPoet = "com.squareup:kotlinpoet:2.2.0"
processing-kotlinPoet-ksp = "com.squareup:kotlinpoet-ksp:2.2.0"

material = "com.google.android.material:material:1.13.0"

lint-checks = "com.android.tools.lint:lint-checks:31.13.0"
lint-api = "com.android.tools.lint:lint-api:31.13.0"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
